applications:
- name: iOS App
  path: /Users/srinivasan.arulsivam/projects/ios/ios_app
  env: {}
  commands:
  - name: Full Build
    steps:
    - git reset --hard origin/master
    - git fetch
    - git checkout master
    - git pull origin master
  - name: Quick Pod Install
    steps:
    - cd HostApp
- name: iOS UI Tests
  path: /Users/srinivasan.arulsivam/projects/automation/ios-ui-tests
  env: {}
  commands:
  - name: Full Build
    steps:
    - git fetch origin
    - git reset --hard
    - git clean -fd
    - git pull origin master
    - cd MCOM && git reset --hard && bundler install && fastlane regenerate_project
      && pod install
    - cd BCOM && bundler install && fastlane regenerate_project && pod install
- name: Android App
  path: /Users/srinivasan.arulsivam/projects/android/android-app
  env:
    JAVA_HOME: /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
  commands: []
- name: Mobile-xAPI
  path: /Users/srinivasan.arulsivam/projects/xapi/CHANGE_ME_TO_YOUR_APP_DIR
  env:
    JAVA_HOME: /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
    MAVEN_HOME: /opt/homebrew/Cellar/maven/3.9.11/bin
  commands: []
- name: BuildPilotGUI
  path: /Users/srinivasan.arulsivam/projects/python/BuildPilotGUI
  env: {}
  commands: []
global_env:
  JAVA_HOME: /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
  MAVEN_HOME: /opt/homebrew/Cellar/maven/3.9.11/bin
  PATH_PREPEND:
  - /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin
  - /opt/apache-maven-3.9.6/bin
